### ISSUE TITLE
Compilation error when compiled with latest code in 'https://github.com/flink-tpc-ds/flink'

### ISSUE THREAD

**Issue by ramkrish86** [flink-tcp-ds/flink-community-perf#1]
When I downloaded the latest tpc-ds based flink version (Version 1.10 SNAPSHOT) and compiled the flink-community-perf tool it has the following compilation errors
`[ERROR] [Error] /home/flink-community-perf/src/main/scala/com/alibaba/flink/benchmark/perf/QueryBenchmark.scala:155: not found: value CsvTableSource2
[ERROR] [Error] /home/flink-community-perf/src/main/scala/com/alibaba/flink/benchmark/perf/QueryBenchmark.scala:169: not found: type ParquetTableSource
[ERROR] [Error] /home/flink-community-perf/src/main/scala/com/alibaba/flink/benchmark/perf/QueryBenchmark.scala:183: not found: value StatisticGenerator
[ERROR] [Error] /home/flink-community-perf/src/main/scala/com/alibaba/flink/benchmark/perf/QueryBenchmark.scala:196: not found: value TableStatsConverter
[ERROR] [Error] /home/flink-community-perf/src/main/scala/com/alibaba/flink/benchmark/perf/QueryBenchmark.scala:197: not found: value TableStatsConverter
[WARNING] [Warn] /home/flink-community-perf/src/main/scala/com/alibaba/flink/benchmark/perf/QueryBenchmark.scala:253: fruitless type test: a value of type Number cannot also be a java.sql.Date
[WARNING] [Warn] /home/flink-community-perf/src/main/scala/com/alibaba/flink/benchmark/perf/QueryBenchmark.scala:259: fruitless type test: a value of type Number cannot also be a java.sql.Date
[WARNING] [Warn] /home/flink-community-perf/src/main/scala/com/alibaba/flink/benchmark/perf/QueryBenchmark.scala:269: fruitless type test: a value of type Number cannot also be a java.sql.Date
[WARNING] [Warn] /home/flink-community-perf/src/main/scala/com/alibaba/flink/benchmark/perf/QueryBenchmark.scala:275: fruitless type test: a value of type Number cannot also be a java.sql.Date
[ERROR] [Error] /home/flink-community-perf/src/main/scala/com/alibaba/flink/benchmark/tools/CsvToParquet.scala:7: object CsvTableSource2 is not a member of package org.apache.flink.table.sources
[ERROR] [Error] /home/flink-community-perf/src/main/scala/com/alibaba/flink/benchmark/tools/CsvToParquet.scala:13: object sinks is not a member of package org.apache.flink.table.planner
[ERROR] [Error] /home/flink-community-perf/src/main/scala/com/alibaba/flink/benchmark/tools/CsvToParquet.scala:30: not found: type ParquetTableSink
[ERROR] [Error] /home/flink-community-perf/src/main/scala/com/alibaba/flink/benchmark/tools/CsvToParquet.scala:100: not found: value CsvTableSource2
`

**Comment by leonardBang** [comment]
@ramkrish86 Please compile flink in branch [tpcds-master](https://github.com/flink-tpc-ds/flink/tree/tpcds-master) , we import parquet Source/Sink  in this branch  rather than  master branch.
BTW，we imported some bugfixes and new features in this branch.

**Comment by ramkrish86** [comment]
@leonardBang  - Thanks for the update. Let me try as per your suggestion.

**Comment by ramkrish86** [comment]
It works now. Thanks a lot.
